clc;
clear;
close all;

highfir = designfilt('highpassfir', ...
    'StopbandFrequency',5000, ...
    'PassbandFrequency',24000, ...
    'PassbandRipple',1, ...
    'StopbandAttenuation',20, ...
    'SampleRate',48000);      % StopbandFrequency截止频率 SampleRate采样率 PassbandFrequency采样率/2

save('highfir.mat', "highfir");